# Generated by Django 4.0.3 on 2022-03-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Short_URls',
            new_name='Short_URL',
        ),
    ]
